### ISSUE TITLE
Maybe a little too fast... 

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#10]
They're wolves not the Flash :P

**Comment by SnowShock35** [comment]
Still in debate... hold this until otherwise said

**Comment by LyraelRayne** [comment]
Uhhh. I may have accidentally left them at ocelot speed :P Let me know. It's easy enough to fix.

**Comment by Jaspanda** [comment]
Agreed, too fast.

**Comment by SnowShock35** [comment]
Okay perhaps slow them down a little. Maybe so they're a little faster than regular wolves so they can keep up with you running without having to teleport but not too fast they become the flash

**Comment by LyraelRayne** [comment]
I've reduced their speed to normal wolf speed. I think they are slightly faster when following their owner though.
