### ISSUE TITLE
Lyrael Everything is Broken D: 

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#17]
http://pastebin.com/g9GCkZQB (1.0.4)

**Comment by LyraelRayne** [comment]
http://data.whicdn.com/images/110756952/large.png

**Comment by LyraelRayne** [comment]
But seriously, I can't get it to do this at all. Made a build, installed pretty much every mod you have in your mods list and it loads just fine.

**Comment by SnowShock35** [comment]
Ah ffs will look into it a little later

**Comment by LyraelRayne** [comment]
Try this file (unzip the jar out of the zip first)
[Stacy'sWolvesMod-1.7.10-1.0.4.jar.zip](https://github.com/LyraelRayne/StacysWolves/files/236546/Stacy.sWolvesMod-1.7.10-1.0.4.jar.zip)

**Comment by SnowShock35** [comment]
K will when I get home at 8pm

**Comment by SnowShock35** [comment]
I officially hate Biomes 'O' Plenty right now :unamused:

**Comment by SnowShock35** [comment]
#blameSnow
