### ISSUE TITLE
Spawn rate

### ISSUE THREAD

**Issue by Awesomepeople4321** [LyraelRayne/StacysWolves#21]
i'm not sure if the mod is supposed to be like this but i loaded a new flat world and there was at least 1000 wolves around me . I flew around for about ten minutes to see if i had just spawned in an area with a bunch of wolves but i could not find a place where i could even see the ground.

**Comment by SnowShock35** [comment]
Yeah we're aware of this issue.

Thanks for the report though. :smile:

**Comment by Awesomepeople4321** [comment]
ok thanks :-1:

**Comment by Awesomepeople4321** [comment]
ok thanks :+1:

**Comment by LyraelRayne** [comment]
At least it's better than the slimes you normally get :P

**Comment by LyraelRayne** [comment]
I'm hopefully going to dedicate some of this weekend to figuring out how to control the spawns better in general.

**Comment by LyraelRayne** [comment]
Annnnd it should be fixed! I completely rewrote spawning and now the wolves have a spawn cap (separate to the mob spawn cap for most of them except zombie/skele/ender). 

Now instead you'll have 50 zombies assaulting the nearest village :P
