### ISSUE TITLE
Wolves wont spawn at all

### ISSUE THREAD

**Issue by crickymc1** [LyraelRayne/StacysWolves#22]
I can not find any wolves in my world and when i get a spawn egg it still does not work im currently using mod version 1.0.4 with forge version 1.7.10

**Comment by Jaspanda** [comment]
Make sure your game is not on peaceful, they don't spawn in peaceful

**Comment by LyraelRayne** [comment]
@crickymc1 did you get this sorted out? Hopefully it was just a matter of being in peaceful mode. Otherwise, try version 1.0.5 . It's the first version that I'd confidently say has good spawn mechanics in place.

**Comment by crickymc1** [comment]
Yes thank you im so stupid :') It was on peaceful but i turned it to normal now it works perfectly, thank you again!

**Comment by LyraelRayne** [comment]
That must make me stupid too then :P I've done that at least 5 times testing the mod because I turn it on and off peaceful to clear the wolves haha. Have fun with the mod!
