### ISSUE TITLE
What do you feed the wolves?

### ISSUE THREAD

**Issue by crickymc1** [LyraelRayne/StacysWolves#23]
i tried feeding the birch wolf a birch sapling as i thought you fed them with whatever you made the bone with and it wouldn't work so i tried the birch bone and it still wouldnt work, what do you feed them with?

**Comment by SnowShock35** [comment]
@crickymc1 You feed them with normal wolf food. See http://minecraft.gamepedia.com/Wolf#Taming.2C_health_and_feeding for more info

**Comment by LyraelRayne** [comment]
That isn't strictly speaking true. They actually should only eat raw beef and raw chicken. 

Eventually I might make them do something more interesting (like blaze wolves eating blaze powder or something).
