### ISSUE TITLE
Mesa Bone and Savanna Bone have the same recipe

### ISSUE THREAD

**Issue by Not-February** [LyraelRayne/StacysWolves#28]
Using 1.0.9 version. The beta on Curseforge, that is.

Both take a dead bush in NEI, but the changelog would indicate that the Savanna bone is supposed to use tall grass?

**Comment by LyraelRayne** [comment]
Fixed in 1.0.10 (70529afd5ef699db8512b7bd27c2ca81274f413b). Thanks for the report.
