### ISSUE TITLE
Wolves not spawning???

### ISSUE THREAD

**Issue by Neston** [LyraelRayne/StacysWolves#30]
I added the mod to my single player modded survival series on my danish channel but none of the wolves are spawning whats wrong???

**Comment by LyraelRayne** [comment]
Can you give me a copy of your forge log? (put it on pastebin and link it here)

Also make sure you're  not in Peaceful difficulty.

**Comment by LyraelRayne** [comment]
Also if you're using a modpack, a link to the pack would be helpful.

**Comment by Neston** [comment]
I made the modpack myself i just put some mods together in one

**Comment by Neston** [comment]
i think im using this version 1.7.10-Forge10.13.4.1481-1.7.10

**Comment by Neston** [comment]
and im not  in peaceful
and there you go http://pastebin.com/RVJjz64L

**Comment by LyraelRayne** [comment]
Your paste only appears to be the first 50 lines and doesn't look like a forge log. I'll need the full fml-client-latest.log (or fml-server-latest.log if you're on a server)

I will say that the mod was developed against forge 1614 and the version you say you're using is a fair bit older. Try upgrading to 1614 and see if that fixes it.

**Comment by Neston** [comment]
okay ima try

**Comment by Neston** [comment]
i updated my Forge still no wolves

**Comment by LyraelRayne** [comment]
OK well I'll need the full log then.

**Comment by Neston** [comment]
where is that??

**Comment by LyraelRayne** [comment]
Should be in the log folder of your modpack.  Log folder is in the same place as your mods folder.

**Comment by LyraelRayne** [comment]
@Neston  are you still having trouble? I haven't heard from you in a while. Can I close this?

**Comment by Neston** [comment]
@LyraelRayne i still have the problems but ive been on vacay soo

**Comment by LyraelRayne** [comment]
See #36
