### ISSUE TITLE
Wolves won't spam. 

### ISSUE THREAD

**Issue by perksofbeingjared** [LyraelRayne/StacysWolves#31]
When I first saw this mod, I was thrilled to start playing with it! So I decided to put tons of my favourite mods together in one folder (including Stacy's Wolves) and I immediately launched the game and started to play it. I started seeing a lot of Zombie wolves, Skeleton wolves but mostly just Ender wolves. I explored a bit more into my world but I couldn't seem to find any other kinds of  wolves other than those three. I even stumbled upon a Savannah and none of the Savannah wolves were to be found. I spent hours in a Roofed forest looking for a mushroom wolf and Deserts were completely empty. I thought maybe it was one of the mods that were in this folder that was causing this but when I created another world with only Stacy's wolves installed... The issue was still there. 

Could you please tell me what's going on? I really do enjoy the concept of this mod and I don't want to give it a bad review. 

P.S. the only other few wolves that I could find were Nether wolves, Blaze wolves, Flower wolves, Birch wolves & Earth wolves... But the rest didn't seem to be spawning in.

**Comment by LyraelRayne** [comment]
Can I get a copy of the latest forge log from your modpack? Chuck it on pastebin.

**Comment by perksofbeingjared** [comment]
http://pastebin.com/yUwU063v

I hope this helps :)

**Comment by LyraelRayne** [comment]
That's the Minecraft log. I need the forge log. It's called fml-client-latest.log (or fml-server-latest.log if you're running a server).

**Comment by perksofbeingjared** [comment]
http://pastebin.com/wCuzgA8c

There!

**Comment by LyraelRayne** [comment]
I notice you appear to be using a modpack that isn't Mystic Mesa. Do you have a link to the pack or is it handcrafted? I'd like to try it out myself to see what's going on.

Do note that wolves are not as common as they have been in Stacy's earlier videos and that you may need to stay in one area for a while to see non "mob" type wolves as they only spawn AFTER a chunk is generated. As such t he best way to find the wolves may be not to look for them. The mob types  (zombie, etc. ) spawn the same way that hostile mobs do. The others spawn the same way that passive creatures (cows, etc.) do (spawn cycle once every few minutes). 

I can see that all of the wolf types appear to be being registering to spawn in a variety of biomes and they all spawn for me.

If you still can't find the mobs you're looking for then try unzipping the attached log4j2.zip into your profile and adding   -Dlog4j.configurationFile=log4j2.xml to the JVM arguments of your profile (you do this in the vanilla launcher that appears after pressing 'play" by clicking "edit profile" and editing the JVM arguments box (ticking it if needed).

Once that's done, play for a while and pastebin a copy of spawnlogger.log

[log4j2.zip](https://github.com/LyraelRayne/StacysWolves/files/415740/log4j2.zip)

**Comment by perksofbeingjared** [comment]
How do I send you my modpack?

**Comment by perksofbeingjared** [comment]
And I don't understand what to add...

**Comment by LyraelRayne** [comment]
If it's a hand crafted modpack there's not really a good way to send it except zipping up your folder and putting it on dropbox.

Are you using the curse app to launch your game?

**Comment by perksofbeingjared** [comment]
https://www.dropbox.com/sh/ddkh6l48bqvpkyz/AADXFaP0hP6htso-sAUTKsHma?dl=0

**Comment by perksofbeingjared** [comment]
It seems to be working... However, skeleton wolves, zombies wolves & ender wolves spawn in day

**Comment by LyraelRayne** [comment]
That.... seems odd. Are you sure they're spawning during the day rather than just surviving from the night before? 

Ender wolves won't despawn and skeleton/zombie wolves will survive during the day if they've been tamed by a player or if they stay in the shade/water.

I've tried your modpack out and from what I can see it appears to be working fine. I also met the fairy queen lol.

**Comment by LyraelRayne** [comment]
@perksofbeingjared are you still having trouble ? Can I close this?

**Comment by LyraelRayne** [comment]
Closing as no further replies have been received.
