### ISSUE TITLE
Spawn rates are abnormally high (Twilight Forest compatibility)

### ISSUE THREAD

**Issue by vatns** [LyraelRayne/StacysWolves#32]
In twilight forest dimension (when the mod installed) spawn rates are abnormally high and cause a lot of lag

Additional info: running with optifine on 1.7.10, MacBook Pro 15 2015, 8 GB of ram allocated for the game.
![2016-08-21_17 28 53](https://cloud.githubusercontent.com/assets/21168593/17846486/74929b48-6851-11e6-9c53-8d22bfafed87.png)

**Comment by LyraelRayne** [comment]
This is a general problem with Twilight Forest and mods which spawn mobs https://github.com/Benimatic/twilightforest/issues/50

Not sure what I can do about this. I'll try and make time to have a look on the weekend.

**Comment by vatns** [comment]
Thanks, you're the best!

**Comment by LyraelRayne** [comment]
I'm pushing a version 1.0.12 which adds a configurable dimension blacklist. An empty list will be added to the configuration file first time 1.0.12 is loaded. If you put dimension 7 (I believe this is the Twilight Forest) into the blacklist, Stacy's Wolves won't spawn there at all.
