### ISSUE TITLE
Certain Types of Wolves Not Spawning

### ISSUE THREAD

**Issue by jlfan4293** [LyraelRayne/StacysWolves#33]
I've been playing a world on minecraft using StacysWolves and I've noticed that certain wolves, such as Mesa Wolves and Cloud Wolves, are not spawning. I know the areas they're meant to spawn in but nothing is there.

**Comment by LyraelRayne** [comment]
Are you able to export your curse profile that is having this problem and upload it somewhere for me? A few people have complained of not getting wolves to spawn but they spawn for me so I'm having trouble reproducing this.

**Comment by LyraelRayne** [comment]
Try the fix in #36
