### ISSUE TITLE
Blank Config File? 

### ISSUE THREAD

**Issue by nothawkeye** [LyraelRayne/StacysWolves#34]
The config file for the mod its completely blank, are there any plans to add some settings in there? Maybe the option to fiddle with the spawn rates of the wolves. Maybe even an option to make tamed dogs immune to dying (my boyfriend and i play together and he almost cries when one of our dogs dies), which i know is probably way too much coding and more like a separate mod altogether but id figure id bring it up. Anyway thanks in advance for reading this!

**Comment by nothawkeye** [comment]
*i meant "is" in the first sentence, sorry about that

**Comment by LyraelRayne** [comment]
In the latest version it shouldn't be blank, but the only setting which exists right now is to blacklist dimensions from having wolves spawn.  In previous versions it would be blank as it only existed due to my setting up the configuration file structure as part of setting up the mod.

**Comment by nothawkeye** [comment]
ah! okay, i guess im missing an update then haha. do you have any plans to add more options to the config?

**Comment by LyraelRayne** [comment]
Not particularly. The mod was pretty much just created for Stacy's let's plays and generally I just set it up how she wants it by default. One day I might add things but right now I'm focusing on other things.

I'm going to close this issue now as there's nothing to be done for it.
