### ISSUE TITLE
Spawn issue

### ISSUE THREAD

**Issue by monagas25** [LyraelRayne/StacysWolves#36]
Hi! I will like to know why must of the wolfs are not spawning.

**Comment by LyraelRayne** [comment]
Most people who have this problem disappear by the time I get back to them. I suspect this means it just takes a while for people to notice them spawning for some people. How long have you been playing?

Also which version of the mod are you using? Are you using a multiplayer server or just playing single player? Are you using other mods or just stacy's wolves? 

Most of that can be found in the log, which you can upload to pastebin and I'll get the info out of it. The log can be found in your minecraft instance directory (found by right clicking on your minecraft profile in Twitch and clicking "open folder", then going to the logs directory). 

I really want to find out why this is happening to some people but it's hard without knowing anything about what circumstances cause it.

**Comment by monagas25** [comment]
Hi! Thanks for answering, I have been playing for like a week, and the only ones I'd seen are the ender, zombie, skeleton and ocean ones. I have the last version that has been release (1.0.13). I did another profile with version before that, and it works great. 
It's a sinlge player. 

https://pastebin.com/v5DwFLu5

I think that's what you asked for haha. I don't really know. I mean, I'm really sorry for bothering you. But I really like this mod. And that last update is the best one.

**Comment by LyraelRayne** [comment]
Alright so it looks like you're using the Mystic Mesa modpack (is that correct?) Have you updated any mods other than stacy's wolves in the modpack? IF so, which versions were updated to?

Can you tell me whether anything else is spawning in your world?

That log looks like the right sort of log, but it's missing all of the startup info (which is the most useful part).

For example I've uploaded a copy of my latest.log https://pastebin.com/VFvAf1d6

Do you have a log that looks like that?

**Comment by LyraelRayne** [comment]
Also thanks for letting me know that the previous version (1.0.12) worked. That's extremely valuable information.

**Comment by monagas25** [comment]
No, It's not that modpack, is one I put together (It has mods of MM but not all of them). And yeah, that version works better, but I like the 1.0.13 because you can command your wolves to wander. 

And yeah, that's the log I send haha.

Also, I think all the other mobs are spawning well.

**Comment by LyraelRayne** [comment]
OK I'm going to try and look into what's changed since 1.0.12 but while I'm doing that you might want to try creating a new profile and copying your world into it (I assume you're using twitch/curse) and see if that helps (as far as i can tell everything works for me on a fresh profile with mystic mesa, but with just stacy's wolves updated).

**Comment by LyraelRayne** [comment]
Just thought of another thing you might check. In the F3 screen, does it say any wolves had spawned? It's possible they're spawning and you're just not finding them. Although one would hope that in a week's play you'd see at least one. I've been playing less than an hour on a fresh world and have 1 dirt wolf and about 20 "mob" wolves (zombie, skeleton, etc.)

You'll need to turn it on by setting debugEnabled in the configuration file for stacy's wolves.

**Comment by monagas25** [comment]
Okay, I'll try that. I mean I believe they are spawning. But now it's like really hard finding them(?) haha I don't know. 

And just thank you for taking your time and help me try to fix this!

**Comment by LyraelRayne** [comment]
No problem. I've been wanting to sort out what's happening with people not being able to spawn wolves (and why Stacy all of a sudden has no hostile mobs spawning) but it's been hard without access to someone who actually has the problem.

**Comment by LyraelRayne** [comment]
So thanks for helping me troubleshoot :)

**Comment by monagas25** [comment]
Oh yeah! I've seen that on her videos.

I'm going to try and find some more wolves :)

And if you need anything else, you can tell me!

**Comment by LyraelRayne** [comment]
I'll tell you this... Minecraft spawning is an unpredictable and frustrating beast!

You wanna try replacing your existing Stacy's Wolves mod JAR with the one I've attached?

Open the mod profile folder like  you did to find the log, then go into mods and remove stacy's wolves and drop this one in.

You will need to unzip the zip file to get the JAR file.

[Stacy'sWolvesMod-1.7.10-1.0.14-PRE.jar.zip](https://github.com/LyraelRayne/StacysWolves/files/999311/Stacy.sWolvesMod-1.7.10-1.0.14-PRE.jar.zip)

**Comment by monagas25** [comment]
Hi! You're the best! I created a new profile just to try it. And I encountered dirt, birch and cloud ones! So I'm pretty sure it works better. 

I just have a question, It is not about an issue though. The mushroom wolves spawn only on Mushroom Islands or they do it on Roofed Forest too? 

Thanks! Now I will put it in the profile I created!

**Comment by LyraelRayne** [comment]
They spawn in the Roofed Forest plus any biome which has the biome dictionary type "MUSHROOM". Which means if there are any extra biomes or biomes o' plenty biomes tagged as mushroom they'll spawn there too.

I think it also will pick any biome whose default top block is mycelium.
