### ISSUE TITLE
Name Tags not working

### ISSUE THREAD

**Issue by jlfan4293** [LyraelRayne/StacysWolves#38]
Hey Lyrael,

I recently started a new world with the updated version of this mod, and I'm having an issue with name tags. I'll use the name tag on any of the modded wolves, and it'll appear to work at first. The whenever I move ANYTHING in my inventory, the name tag will reappear, but the name will appear to stay on the wolf as well. But the moment I re-log, the wolves are unnamed again. I haven't been able to figure out how to fix this. I'm not having this problem with unmodded animals, and I don't have any other animal mods. 

Thanks in advance!

**Comment by LyraelRayne** [comment]
That's very odd. I'll try and reproduce this. Thanks for the report.

Are you running on a server, or single player?

**Comment by jlfan4293** [comment]
I'm running on my own single player world. I can send an image of the other mods i'm using if that would help, though most of them are already found in the Mystic Mesa modpack.

**Comment by LyraelRayne** [comment]
No need for that. I just reproduced it with minimal mods installed. Seems to only happen for tamed wolves so I think I know where to look for the bug.

**Comment by LyraelRayne** [comment]
I'm looking into this now and I've discovered that shift-right clicking on a tamed wolf with the name tag will allow the tag to work. I still need to fix non-shift clicking but thought you might want to know so you can use name tags in the meantime.

**Comment by LyraelRayne** [comment]
Fixed in 1.1.1

**Comment by jlfan4293** [comment]
Thanks for letting me know! I'll definitely try that next time I'm on the world.
