### ISSUE TITLE
Stop spawning wolves in a certain dimension...

### ISSUE THREAD

**Issue by Charizard694** [LyraelRayne/StacysWolves#39]
Hi guys!

Can anyone tell/show me what exactly to put down in the config next to blacklisting dimensions so wolves don't spawn in that map? The dimension id/name is UW_GARDEN_2

Where and how would I input that in the config line of
```
# List of dimensions to NEVER spawn Stacy's Wolves in.
I:dimensionSpawnBlackList <
 >
```
Thanks in advance :)

**Comment by LyraelRayne** [comment]
That doesn't look like a dimension ID to me. Dimension IDs are numbers. That looks more like a biome within that dimension.

I don't know of any easy way of finding which dimension matches which ID, but usually the mod which adds a dimension lets you set what the ID is in configuration, and the mod's configuration contains the default. You can also look in your saves/<your world name here> folder and you'll see a bunch of DIM# folders where # is the dimension ID. (DIM-1 is dimension -1 which is the nether. DIM1 is The End, etc.) If there aren't a lot of different dimensions then maybe you can see which one.

When you do ultimately find out the correct ID, simply put the number on a line by itself between the < and the > like so

```
I:dimensionSpawnBlackList <
   7
>
```

Without knowing what mod the dimension is from I can't provide much more help than that I'm afraid.

**Comment by Charizard694** [comment]
Ahh thank you soo much! The dimension ID is 2 (well from what I could assumed in the folder title - "UW_GARDEN_2") tested it and worked a-okay. :)
