### ISSUE TITLE
Stacy's Wolves logs every single potential wolf spawn regardless of whether they actually spawn, causing massive log file bloat

### ISSUE THREAD

**Issue by Not-February** [LyraelRayne/StacysWolves#46]
This is the only reason I don't want to use this mod in my 1.7.10 setups anymore. It not only makes it difficult to find relevant logging for debugging other issues, but in extended sessions the log file can easily become GB in filesize at an alarming rate due to Stacy's Wolves alone.

The log I'm providing was from running a single player world with nothing but ``Stacy's Wolves 1.1.4`` and Forge ``10.13.4.1614``  installed for maybe.... two minutes or so, and then closing the game, and it's already 1,720kb in size. I actually can't even copy its entire contents into a gist without Github timing out, so here's the file itself.

[fml-client-latest.log](https://github.com/LyraelRayne/StacysWolves/files/7272598/fml-client-latest.log)

**Comment by LyraelRayne** [comment]
Hi there,

For some reason I didn't realise that Forge is turning on Trace and Debug logging by default (or perhaps MultiMC is what's doing that?, it doesn't seem to appear when running through CurseForge). I've made the verbose logging optional (turned off by default) in version 1.1.5. Please try it and close this issue if that fixes it for you.

**Comment by Not-February** [comment]
Oh wow! That was a fast response. I've given it a try and the logging issue is definitely resolved!

...That said I regret to inform you that squid wolf spawning is still absolutely ridiculous. I caught this while the world was still loading. As this is unrelated to the issue I originally posted, I'll close this for now.

![image](https://user-images.githubusercontent.com/13922447/135970062-6e2bb027-19d0-46cc-a111-328c51e5775c.png)

**Comment by LyraelRayne** [comment]
Haha yeah I don't think there's much I can do about squid wolves. Minecraft spawning wants to fill that cap with anything it can find, and in some places all it can find is Squid Wolves :P
