### ISSUE TITLE
Some misc. crashes

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#5]
[crash-2016-04-22_21.59.48-client.txt](https://github.com/LyraelRayne/StacysWolves/files/232577/crash-2016-04-22_21.59.48-client.txt)
[crash-2016-04-22_22.04.22-client.txt](https://github.com/LyraelRayne/StacysWolves/files/232578/crash-2016-04-22_22.04.22-client.txt)
[crash-2016-04-22_22.12.33-client.txt](https://github.com/LyraelRayne/StacysWolves/files/232579/crash-2016-04-22_22.12.33-client.txt)

Some Miscellaneous crashes I experienced with the mod while testing

**Comment by LyraelRayne** [comment]
Ahah! Deobfuscation related bug. 

IRenderableWolf had a method with the same name as the unobfuscated method in Entity. When the re-obfuscator changes the name back, the interface is no longer correctly implemented.

Had to change the name of the interface method to not match an Entity method, then implement it as a wrapper around the Entity method.

Mostly writing this for @AKTheKnight 's benefit in case he runs into it in one of his mods as it took me hours to figure this out the first time I ever saw it ;)
